### ISSUE TITLE
Document and improve policy on incompatible API updates

### ISSUE THREAD

**Issue by aeijdenberg** [cloudfoundry-incubator/credhub#49] opened 2018-10-11 04:56 UTC
After a recent credhub update, we noted today that part of our infrastructure began receiving the error:

```json
{"error":"The request includes an unrecognized parameter 'overwrite'. Please update or remove this parameter and retry your request."}
```

from `PUT` requests to `/api/v1/data` that contained `"overwrite":true`.

The fix (for us) was to convert to `"mode":"overwrite"`.

Can someone please explain why the API is versioned, yet an incompatible change like this did not result in a bump to `v2`? (and, for trivial cases like this, the previous version signature still supported under the old path?) I would have thought that was the point of having a version as part of the API endpoint path?

Google seem to do a reasonably good job at this, it might be worth reading Dan Ciruli's blog post about it: <https://cloud.google.com/blog/products/gcp/versioning-apis-at-google>

See also related https://github.com/cloudfoundry-incubator/credhub-cli/issues/50 - and thank you for fixing that.

**Comment by aeijdenberg** [comment] 2018-10-11 05:51
Actually I spoke too soon. That change above also fails with:

```json
{"error":"The request includes an unrecognized parameter 'mode'. Please update or remove this parameter and retry your request."}
```

Verifying the version:

```bash
curl -k -H "Authorization: bearer $AT" https://localhost:8844/version
{"version":"2.0.2"}
```

Simple `PUT` with `mode`:

```bash
curl -k -H "Authorization: bearer $AT" https://localhost:8844/api/v1/data --data '{"name":"/foo","type":"value","value":"bar","mode":"overwrite"}' -X PUT -H "Content-Type: application/json"
{"error":"The request includes an unrecognized parameter 'mode'. Please update or remove this parameter and retry your request."}
```

Try without `mode`:

```bash
curl -k -H "Authorization: bearer $AT" https://localhost:8844/api/v1/data --data '{"name":"/foo","type":"value","value":"bar"}' -X PUT -H "Content-Type: application/json"
{"error":"The request could not be completed because the credential does not exist or you do not have sufficient authorization."}
```

I'm fairly sure these credentials do have permissions and ii's correct that it doesn't exist, that's why I'm trying to set it.

I'm pretty confused by how to set values in 2.0.x?

**Comment by aeijdenberg** [comment] 2018-10-11 06:05
The API docs for 2.0.0 state that `mode` is supported for set credential requests:
http://credhub-api.cfapps.io/version/2.0/#set-credentials

The release notes for 2.0.0 state that:
> overwrite mode no longer exists for set requests. Set always overwrites data that already exists.

(ironically the opposite position of what the credhub CLI version 2.0.0 did)

I also see there the note re changing of how permissions work, which explains the last issue above - rolling that out now to test.

**Comment by aeijdenberg** [comment] 2018-10-11 06:08
And it does. And removing `mode` seems to work.

Wow. This overwrite change sure has been a journey. Reinstating original bug title - why the incompatible API change without revving API version numbers?

**Comment by chhhavi** [comment] 2018-10-11 15:43
Our API docs are out of date. We have a story to fix them [here](https://www.pivotaltracker.com/story/show/160767524). The incompatible API change was made from 1.9.x to 2.0.x. We bumped a major version when making these changes. Removing mode and overwrite from the server/cli would have been clean except the bosh team relied on the unintended behavior of credentials not being overwritten. After we released 2.0, the bosh team asked that we revert those changes, which we did. But it meant that there was a lot of back and forth with those parameters. It definitely did not go as smooth as intended. Sorry for any lost time, the CredHub team appreciates your patience. Albeit, the release notes and documentation processes need work.

**Comment by crawsible** [comment] 2018-10-11 18:57
@aeijdenberg All valid points and we recognize that we've been falling down a bit in the past few months with respect to versioning and documentation. For context, our team is focused almost entirely on three consumers above all others: BOSH, Cloud Foundry, and Concourse. Put another way, we emphasize communicating and coordinating with those projects directly over general usability, and we view CredHub as a component of those systems rather than as a standalone product.

None of this is to say that we won't be taking your feedback to heart, but I want to be honest with you as to where our priorities lie. That said, updating our docs to address the inconsistencies you and others have run into is the next item in our backlog, and we'll reach out again on this issue when we're confident in their veracity.

Thanks again for reporting and bearing with us.

**Comment by jparnala** [comment] 2018-12-04 18:59
CredHub API documentation has been updated here: 
http://credhub-api.cfapps.io/version/2.1/#credentials

Closing, please re-open if you have any remaining issues.

**Closed by jparnala** 2018-12-04 18:59 UTC
Labels: unscheduled
