### ISSUE TITLE
Clarify behavior when setting credentials without overwrite flag

### ISSUE THREAD

**Issue by ctaymor** [cloudfoundry-incubator/credhub#15] opened 2017-06-09 16:50 UTC
When trying to set a credential in the API with a previous value without the overwrite flag, we were surprised that we got a 200 Success but the value didn't change 

We would have expected to get a 403 Forbidden or maybe a 409 Conflict when the variable already has a value, and the overwrite key is not provided, so the value can't (and won't) be persisted. It would be great to either return a clearer error code, or if it's not a bug, document the behavior in the case explicitly.

**Comment by pivotal-danjahner** [comment] 2017-07-05 23:58
Hey Caroline, 

Sorry for the delay. Returning a 200 and the stored value in the case where a credential exists is the intended behavior of `overwrite: false` (which is also the default behavior). Our intention is to add safety for stored values and to create an idempotent interaction for consumers that want to generate values without separately checking for a previously stored value (and avoid the TOCTOU race condition of that interaction). 

We have some documentation on that functionality in our [api docs][1], although that isn't as prominent as we could hope. I'll see what we can do to make that more clear. 

[1]:https://credhub-api.cfapps.io/#overwriting-credential-values

**Comment by martys34** [comment] 2018-09-27 14:44
@jagadish-kb Setting overwrite automatically creates a new version of the credential so there is no way to overwrite the old version with a new value.
You are correct in assuming that the result array is sorted in DESC order based on creation time.

Closing because the behavior of the original issue has been documented.

**Closed by martys34** 2018-09-27 14:44 UTC
Labels: planned
